### ISSUE TITLE
Test if blockstack works well within a Chrome extension

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/discussify#3]
The plan is to have discussify as:

1. A regular web-app
2. A extension to easily discuss URIs
3. An embed so that developers can embed discussions on stuff like articles, news, etc.

Making an extension is probably the easiest of all and goes well with the amount of features the MVP will have. Still, we must be sure that blockstack authentication works well with extensions.

**Comment by satazor** [comment]
https://forum.blockstack.org/t/got-a-few-questions-considering-using-blockstack/5608

**Comment by satazor** [comment]
After some tests, blockstack does not work inside extensions because: 

- It tries to do `window.location = ‘blockstack:xxx’ which fails in extensions
- Even if the previous point was somehow fixed, chrome extensions do not have a regular "origin/domain"

![untitled 3](https://user-images.githubusercontent.com/1017236/41974893-1f71883a-7a11-11e8-9fb6-863778041d53.gif)

I will try to go with a "inject code" approach instead and will report back.

**Comment by satazor** [comment]
I've tried the "inject code" approach and hit another issue, and this is a very hard one..

1 - User enters `xxx.com` and clicks "Login with blockstack" 
2 - User is redirected to `http://localhost:8888/auth?authRequest=eyJ0e...` where he approves the "login". Note that this page is being served by a locally installed Blockstack app.
3 - At this page, Blockstack attempts to fetch `manifest.json` file from `xxx. com/manifest.json` for some reason, probably to retrieve configuration & permissions requested
4 - This request fails for most sites because there's no `Access-Control-Allow-Origin` header that allows `localhost:8888` to fetch that page...

I've never hit this issue before because I'm been using some demo applications that already had a server in place with that header. Nevertheless, we can't get around this because we do not control the servers from the sites where people will be using Discussify.

This is a major issue.. I'm considering switching to uport again and put the "app-secret" in the source-code until they add a p2p flow as discussed here: https://github.com/uport-project/docs/issues/18#issuecomment-398422913

//cc @diasdavid

**Comment by marcooliveira** [comment]
This is unfortunate. What if, instead, we inject an iframe to something that we're hosting, which we would control and add CORS?

**Comment by satazor** [comment]
@marcooliveira that can work indeed, I will try it out.

**Comment by satazor** [comment]
Possible solution for the CSP blocking: https://transitory.technology/browser-extensions-and-csp-headers/
