### ISSUE TITLE
Update all user-journeys mockups to use blockstack

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/discussify#5]
All the mockups should use blockstack for the identity/authentication part.

**Comment by satazor** [comment]
When #3 is done, we should schedule a meeting with @diasdavid to decide if we go with the extension or the website.

**Comment by satazor** [comment]
@diasdavid The extension will have an option to expand into a larger view. For now, due to time constraints, we must opt for either the website and the extension. Later on, a lot of code can be reused in both codebases.

**Comment by andreforsousa** [comment]
This issue was already solved here: https://github.com/ipfs-shipyard/discussify/issues/12
