### ISSUE TITLE
Add reasoning

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/discussify#9]
Basically a document where we describe the product, its concept among other things.

**Comment by marcooliveira** [comment]
I put an initial reasoning, but there are several areas lacking. We need to discuss and see how we want to proceed. Time is a big constraint right now.

**Comment by marcooliveira** [comment]
I believe that, considering our current time limitations, we should move on, keep as is in terms of amount of content, and keep iterating on it as necessary.
